fix(main): polyfill missing DesktopTTIAnalytics methods on latest PTB
Fixes a crash where core.asar (the downloaded update) expects new telemetry methods to exist on the analytics instance instantiated from app.asar (the host app), which results in TypeError: track... is not a function and causes the client to fail.